// Star Realms base set card definitions.
// 80-card trade deck + starters (Scout, Viper) + Explorers.

import type { CardDef, Effect, Faction } from "./types.js";

const trade = (amount: number): Effect => ({ kind: "trade", amount });
const combat = (amount: number): Effect => ({ kind: "combat", amount });
const authority = (amount: number): Effect => ({ kind: "authority", amount });
const draw = (amount = 1): Effect => ({ kind: "draw", amount });
const oppDiscard = (amount = 1): Effect => ({ kind: "opponent_discard", amount });
const scrapHandOrDiscard = (max = 1): Effect => ({ kind: "scrap_hand_or_discard", max });
const scrapTradeRow: Effect = { kind: "scrap_trade_row" };
const destroyBase: Effect = { kind: "destroy_base" };
const choose = (...options: { label: string; effects: Effect[] }[]): Effect => ({
  kind: "choose",
  options,
});

export const STARTER_SCOUT = "scout";
export const STARTER_VIPER = "viper";
export const EXPLORER = "explorer";

const starters: CardDef[] = [
  {
    id: STARTER_SCOUT,
    name: "Scout",
    faction: "neutral",
    type: "ship",
    cost: 0,
    primary: [trade(1)],
    count: 0,
  },
  {
    id: STARTER_VIPER,
    name: "Viper",
    faction: "neutral",
    type: "ship",
    cost: 0,
    primary: [combat(1)],
    count: 0,
  },
  {
    id: EXPLORER,
    name: "Explorer",
    faction: "neutral",
    type: "ship",
    cost: 2,
    primary: [trade(2)],
    scrap: [combat(2)],
    count: 0,
  },
];

const tradeFederation: CardDef[] = [
  {
    id: "federation_shuttle",
    name: "Federation Shuttle",
    faction: "trade_federation",
    type: "ship",
    cost: 1,
    primary: [trade(2)],
    ally: [authority(4)],
    count: 3,
  },
  {
    id: "cutter",
    name: "Cutter",
    faction: "trade_federation",
    type: "ship",
    cost: 2,
    primary: [authority(4), trade(2)],
    ally: [combat(4)],
    count: 3,
  },
  {
    id: "embassy_yacht",
    name: "Embassy Yacht",
    faction: "trade_federation",
    type: "ship",
    cost: 3,
    primary: [authority(3), trade(2), { kind: "draw_if_bases", bases: 2, amount: 2 }],
    count: 2,
  },
  {
    id: "freighter",
    name: "Freighter",
    faction: "trade_federation",
    type: "ship",
    cost: 4,
    primary: [trade(4)],
    ally: [{ kind: "next_ship_to_top" }],
    count: 2,
  },
  {
    id: "trade_escort",
    name: "Trade Escort",
    faction: "trade_federation",
    type: "ship",
    cost: 5,
    primary: [authority(4), combat(4)],
    ally: [draw(1)],
    count: 1,
  },
  {
    id: "flagship",
    name: "Flagship",
    faction: "trade_federation",
    type: "ship",
    cost: 6,
    primary: [combat(5), draw(1)],
    ally: [authority(5)],
    count: 1,
  },
  {
    id: "command_ship",
    name: "Command Ship",
    faction: "trade_federation",
    type: "ship",
    cost: 8,
    primary: [authority(4), combat(5), draw(2)],
    ally: [destroyBase],
    count: 1,
  },
  {
    id: "trading_post",
    name: "Trading Post",
    faction: "trade_federation",
    type: "base",
    cost: 3,
    defense: 4,
    outpost: true,
    primary: [
      choose(
        { label: "1 Authority", effects: [authority(1)] },
        { label: "1 Trade", effects: [trade(1)] },
      ),
    ],
    scrap: [combat(3)],
    count: 2,
  },
  {
    id: "barter_world",
    name: "Barter World",
    faction: "trade_federation",
    type: "base",
    cost: 4,
    defense: 4,
    primary: [
      choose(
        { label: "2 Authority", effects: [authority(2)] },
        { label: "2 Trade", effects: [trade(2)] },
      ),
    ],
    scrap: [combat(5)],
    count: 2,
  },
  {
    id: "defense_center",
    name: "Defense Center",
    faction: "trade_federation",
    type: "base",
    cost: 5,
    defense: 5,
    outpost: true,
    primary: [
      choose(
        { label: "3 Authority", effects: [authority(3)] },
        { label: "2 Combat", effects: [combat(2)] },
      ),
    ],
    ally: [combat(2)],
    count: 1,
  },
  {
    id: "port_of_call",
    name: "Port of Call",
    faction: "trade_federation",
    type: "base",
    cost: 6,
    defense: 6,
    outpost: true,
    primary: [trade(3)],
    scrap: [draw(1), destroyBase],
    count: 1,
  },
  {
    id: "central_office",
    name: "Central Office",
    faction: "trade_federation",
    type: "base",
    cost: 7,
    defense: 6,
    primary: [trade(2), { kind: "next_ship_to_top" }],
    ally: [draw(1)],
    count: 1,
  },
];

const blob: CardDef[] = [
  {
    id: "blob_fighter",
    name: "Blob Fighter",
    faction: "blob",
    type: "ship",
    cost: 1,
    primary: [combat(3)],
    ally: [draw(1)],
    count: 3,
  },
  {
    id: "trade_pod",
    name: "Trade Pod",
    faction: "blob",
    type: "ship",
    cost: 2,
    primary: [trade(3)],
    ally: [combat(2)],
    count: 3,
  },
  {
    id: "battle_pod",
    name: "Battle Pod",
    faction: "blob",
    type: "ship",
    cost: 2,
    primary: [combat(4), scrapTradeRow],
    ally: [combat(2)],
    count: 2,
  },
  {
    id: "ram",
    name: "Ram",
    faction: "blob",
    type: "ship",
    cost: 3,
    primary: [combat(5)],
    ally: [combat(2)],
    scrap: [trade(3)],
    count: 2,
  },
  {
    id: "blob_destroyer",
    name: "Blob Destroyer",
    faction: "blob",
    type: "ship",
    cost: 4,
    primary: [combat(6)],
    ally: [destroyBase, scrapTradeRow],
    count: 2,
  },
  {
    id: "battle_blob",
    name: "Battle Blob",
    faction: "blob",
    type: "ship",
    cost: 6,
    primary: [combat(8)],
    ally: [draw(1)],
    scrap: [combat(4)],
    count: 1,
  },
  {
    id: "blob_carrier",
    name: "Blob Carrier",
    faction: "blob",
    type: "ship",
    cost: 6,
    primary: [combat(7)],
    ally: [{ kind: "acquire_free_ship_to_top" }],
    count: 1,
  },
  {
    id: "mothership",
    name: "Mothership",
    faction: "blob",
    type: "ship",
    cost: 7,
    primary: [combat(6), draw(1)],
    ally: [draw(1)],
    count: 1,
  },
  {
    id: "blob_wheel",
    name: "Blob Wheel",
    faction: "blob",
    type: "base",
    cost: 3,
    defense: 5,
    primary: [combat(1)],
    scrap: [trade(3)],
    count: 3,
  },
  {
    id: "the_hive",
    name: "The Hive",
    faction: "blob",
    type: "base",
    cost: 5,
    defense: 5,
    primary: [combat(3)],
    ally: [draw(1)],
    count: 1,
  },
  {
    id: "blob_world",
    name: "Blob World",
    faction: "blob",
    type: "base",
    cost: 8,
    defense: 7,
    primary: [
      choose(
        { label: "5 Combat", effects: [combat(5)] },
        {
          label: "Draw a card for each Blob card played this turn",
          effects: [{ kind: "draw_per_faction_played", faction: "blob" }],
        },
      ),
    ],
    count: 1,
  },
];

const machineCult: CardDef[] = [
  {
    id: "trade_bot",
    name: "Trade Bot",
    faction: "machine_cult",
    type: "ship",
    cost: 1,
    primary: [trade(1), scrapHandOrDiscard()],
    ally: [combat(2)],
    count: 3,
  },
  {
    id: "missile_bot",
    name: "Missile Bot",
    faction: "machine_cult",
    type: "ship",
    cost: 2,
    primary: [combat(2), scrapHandOrDiscard()],
    ally: [combat(2)],
    count: 3,
  },
  {
    id: "supply_bot",
    name: "Supply Bot",
    faction: "machine_cult",
    type: "ship",
    cost: 3,
    primary: [trade(2), scrapHandOrDiscard()],
    ally: [combat(2)],
    count: 3,
  },
  {
    id: "patrol_mech",
    name: "Patrol Mech",
    faction: "machine_cult",
    type: "ship",
    cost: 4,
    primary: [
      choose(
        { label: "3 Trade", effects: [trade(3)] },
        { label: "5 Combat", effects: [combat(5)] },
      ),
    ],
    ally: [scrapHandOrDiscard()],
    count: 2,
  },
  {
    id: "stealth_needle",
    name: "Stealth Needle",
    faction: "machine_cult",
    type: "ship",
    cost: 4,
    primary: [{ kind: "copy_ship" }],
    count: 1,
  },
  {
    id: "battle_mech",
    name: "Battle Mech",
    faction: "machine_cult",
    type: "ship",
    cost: 5,
    primary: [combat(4), scrapHandOrDiscard()],
    ally: [draw(1)],
    count: 1,
  },
  {
    id: "missile_mech",
    name: "Missile Mech",
    faction: "machine_cult",
    type: "ship",
    cost: 6,
    primary: [combat(6), destroyBase],
    ally: [draw(1)],
    count: 1,
  },
  {
    id: "battle_station",
    name: "Battle Station",
    faction: "machine_cult",
    type: "base",
    cost: 3,
    defense: 5,
    outpost: true,
    primary: [],
    scrap: [combat(5)],
    count: 2,
  },
  {
    id: "mech_world",
    name: "Mech World",
    faction: "machine_cult",
    type: "base",
    cost: 5,
    defense: 6,
    outpost: true,
    primary: [],
    allyAllFactions: true,
    count: 1,
  },
  {
    id: "junkyard",
    name: "Junkyard",
    faction: "machine_cult",
    type: "base",
    cost: 6,
    defense: 5,
    outpost: true,
    primary: [scrapHandOrDiscard()],
    count: 1,
  },
  {
    id: "machine_base",
    name: "Machine Base",
    faction: "machine_cult",
    type: "base",
    cost: 7,
    defense: 6,
    outpost: true,
    primary: [{ kind: "draw_then_scrap_hand" }],
    count: 1,
  },
  {
    id: "brain_world",
    name: "Brain World",
    faction: "machine_cult",
    type: "base",
    cost: 8,
    defense: 6,
    outpost: true,
    primary: [{ kind: "scrap_hand_or_discard_draw", max: 2 }],
    count: 1,
  },
];

const starEmpire: CardDef[] = [
  {
    id: "imperial_fighter",
    name: "Imperial Fighter",
    faction: "star_empire",
    type: "ship",
    cost: 1,
    primary: [combat(2), oppDiscard()],
    ally: [combat(2)],
    count: 3,
  },
  {
    id: "corvette",
    name: "Corvette",
    faction: "star_empire",
    type: "ship",
    cost: 2,
    primary: [combat(1), draw(1)],
    ally: [combat(2)],
    count: 2,
  },
  {
    id: "survey_ship",
    name: "Survey Ship",
    faction: "star_empire",
    type: "ship",
    cost: 3,
    primary: [trade(1), draw(1)],
    scrap: [oppDiscard()],
    count: 3,
  },
  {
    id: "imperial_frigate",
    name: "Imperial Frigate",
    faction: "star_empire",
    type: "ship",
    cost: 3,
    primary: [combat(4), oppDiscard()],
    ally: [combat(2)],
    scrap: [draw(1)],
    count: 3,
  },
  {
    id: "battlecruiser",
    name: "Battlecruiser",
    faction: "star_empire",
    type: "ship",
    cost: 6,
    primary: [combat(5), draw(1)],
    ally: [oppDiscard()],
    scrap: [draw(1), destroyBase],
    count: 1,
  },
  {
    id: "dreadnaught",
    name: "Dreadnaught",
    faction: "star_empire",
    type: "ship",
    cost: 7,
    primary: [combat(7), draw(1)],
    scrap: [combat(5)],
    count: 1,
  },
  {
    id: "recycling_station",
    name: "Recycling Station",
    faction: "star_empire",
    type: "base",
    cost: 4,
    defense: 4,
    outpost: true,
    primary: [
      choose(
        { label: "1 Trade", effects: [trade(1)] },
        {
          label: "Discard up to 2 cards, then draw that many",
          effects: [{ kind: "discard_then_draw", max: 2 }],
        },
      ),
    ],
    count: 2,
  },
  {
    id: "space_station",
    name: "Space Station",
    faction: "star_empire",
    type: "base",
    cost: 4,
    defense: 4,
    outpost: true,
    primary: [combat(2)],
    ally: [combat(2)],
    scrap: [trade(4)],
    count: 2,
  },
  {
    id: "war_world",
    name: "War World",
    faction: "star_empire",
    type: "base",
    cost: 5,
    defense: 4,
    outpost: true,
    primary: [combat(3)],
    ally: [combat(4)],
    count: 1,
  },
  {
    id: "royal_redoubt",
    name: "Royal Redoubt",
    faction: "star_empire",
    type: "base",
    cost: 6,
    defense: 6,
    outpost: true,
    primary: [combat(3)],
    ally: [oppDiscard()],
    count: 1,
  },
  {
    id: "fleet_hq",
    name: "Fleet HQ",
    faction: "star_empire",
    type: "base",
    cost: 8,
    defense: 8,
    primary: [{ kind: "ships_combat_bonus", amount: 1 }],
    count: 1,
  },
];

export const ALL_CARDS: CardDef[] = [
  ...starters,
  ...tradeFederation,
  ...blob,
  ...machineCult,
  ...starEmpire,
];

export const CARD_INDEX: Record<string, CardDef> = Object.fromEntries(
  ALL_CARDS.map((c) => [c.id, c]),
);

export function getCardDef(defId: string): CardDef {
  const def = CARD_INDEX[defId];
  if (!def) throw new Error(`Unknown card def: ${defId}`);
  return def;
}

/** Definitions that make up the 80-card trade deck (with counts). */
export const TRADE_DECK_DEFS: CardDef[] = ALL_CARDS.filter((c) => c.count > 0);

export const FACTION_LABEL: Record<Faction, string> = {
  trade_federation: "Trade Federation",
  blob: "Blob",
  machine_cult: "Machine Cult",
  star_empire: "Star Empire",
  neutral: "Neutral",
};

export const STARTING_AUTHORITY = 50;
export const STARTING_SCOUTS = 8;
export const STARTING_VIPERS = 2;
export const EXPLORER_COUNT = 10;
export const TRADE_ROW_SIZE = 5;
export const HAND_SIZE = 5;
export const FIRST_TURN_HAND_SIZE = 3;
